
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: utf-8

development:
  <<: *default
  database: blog_development

test:
  <<: *default
  database: blog_test

production:
  <<: *default
  database: blog_production
